site_name: SAP CNW User Guide

nav:
    - Introduction: 'index.md'
    - Pembelian :
        - Pembelian Aktiva : index_pactiva.md
        - Pembelian Barang Dagang : 
            - Prosedur : ap_sop.md
            - Report : apr_sop.md
    - Penjualan :
        - Penjualan Barang Dagang : 
            - Prosedur : ar_sop.md
            - Report : arr_sop.md
theme : readthedocs   
plugins:
    - search 
    - mermaid2
