site_name: SAP User Guide

nav:
    - Introduction: 'index.md'
    - Pembelian :
        - Pembelian Aktiva : index_pactiva.md 
    - Penjualan :
        - Trading Term : tradingTerm.md
        - Sales Order : SalesorderList.md
    - Accounting : 
        - Jurnal Entry : index_je.md
theme : readthedocs   
plugins:
    - search 
    - mermaid2
