site_name: SAP User Guide

nav:
    - Introduction: 'index.md'
    - Pembelian :
        - Pembelian Aktiva : index_pactiva.md 
    - Penjualan :
        - Trading Term : tradingTerm.md
        - Sales Order List : SalesorderList.md
        
theme : readthedocs   
plugins:
    - search 
    - mermaid2
