site_name: My Docs 

nav:
    - Introduction: 'index.md'
    - 'Issue Tracker': 'https://example.com/'
plugins:
    - search
    - mermaid
# Optionally declare the Python requirements required to build your docs

