site_name: SAP User Guide

nav:
    - Introduction: 'index.md'
    - Pembelian :
        - Pembelian Aktiva : index_pactiva.md
        - Pembelian Barang Dagang : ap_sop.md
    - Penjualan :
        - Penjualan Barang Dagang : ar_sop.md
theme : material   
plugins:
    - search 
    - mermaid2 
    - mkdocs_pymdownx_material_extras
